#!/bin/bash

# Run your script
ratio1=12
ratio2=15

#PBS -l select=1:ncpus=32
#PBS -l walltime=00:20:00
#PBS -q debug
#PBS -P hpc2601012
#PBS -N train_${ratio1}_${ratio2}
#PBS -j oe
#PBS -o /mnt/home/project/cshukla.gitika/log/pipeline_${ratio1}_${ratio2}.log

cd $PBS_O_WORKDIR

echo "Job started at: $(date)"

start_time=$(date +%s)

# Initialize conda (IMPORTANT)
source ~/anaconda3/etc/profile.d/conda.sh

# Activate your environment
conda activate genenv_gitika

# Pass these using qsub -v or define here
RSRP1=$ratio1
RSRP2=$ratio2
SEED=123

python3 << EOF
import json

rsrp1 = int("$RSRP1")
rsrp2 = int("$RSRP2")
seed = int("$SEED")

# Input JSON path
input_file = "../Config/demo_config.json"

# Read original JSON
with open(input_file, "r") as f:
    config = json.load(f)

# Update values
config["rsrp1"] = rsrp1
config["rsrp2"] = rsrp2
config["seed"] = seed

# Output filename
outfile = f"../Config/train_{rsrp1}_{rsrp2}.json"

# Save updated JSON
with open(outfile, "w") as f:
    json.dump(config, f, indent=4)

print(f"Created: {outfile}")
EOF


MASTER_LOG="gene_time.log"

start_time=$(date +%s)

echo "==================================" >> $MASTER_LOG
echo "Pipeline started at: $(date)" >> $MASTER_LOG
echo "==================================" >> $MASTER_LOG

python ../clean_codes_v2/run_train_pipeline.py --config-file ../Config/train_${ratio1}_${ratio2} --train 0 --N 1 --fresh_run 1 > train_${ratio1}_${ratio2}_N1.log 2>&1 && \
python ../clean_codes_v2/run_train_pipeline.py --config-file ../Config/train_${ratio1}_${ratio2} --train 0 --N 2 --fresh_run 1 > train_${ratio1}_${ratio2}_N2.log 

end_time=$(date +%s)

echo "Pipeline ended at: $(date)" >> $MASTER_LOG
echo "Total Time: $((end_time - start_time)) seconds" >> $MASTER_LOG
echo "==================================" >> $MASTER_LOG


