#!/bin/bash

# Run your script
ratio1=12
ratio2=15

#PBS -l select=1:ncpus=32
#PBS -l walltime=00:20:00
#PBS -q debug
#PBS -P hpc2601012
#PBS -N train_${ratio1}_${ratio2}
#PBS -j oe
#PBS -o /mnt/home/project/cshukla.gitika/log/pipeline_${ratio1}_${ratio2}.log

cd $PBS_O_WORKDIR

echo "Job started at: $(date)"

start_time=$(date +%s)

# Initialize conda (IMPORTANT)
source ~/anaconda3/etc/profile.d/conda.sh

# Activate your environment
conda activate genenv_gitika

# Pass these using qsub -v or define here
RSRP1=$ratio1
RSRP2=$ratio2
SEED=123


MASTER_LOG="pipeline_time.log"

start_time=$(date +%s)

echo "==================================" >> $MASTER_LOG
echo "Pipeline started at: $(date)" >> $MASTER_LOG
echo "==================================" >> $MASTER_LOG

python clean_codes_v2/run_train_pipeline.py --config-file ../Config/train_${ratio1}_${ratio2} --train 1  > train_${ratio1}_${ratio2}.log

end_time=$(date +%s)

echo "Pipeline ended at: $(date)" >> $MASTER_LOG
echo "Total Time: $((end_time - start_time)) seconds" >> $MASTER_LOG
echo "==================================" >> $MASTER_LOG


